spring:
  security:
    user:
      name: ${ADMIN_SERVER_USERNAME}
      password: ${ADMIN_SERVER_PASSWORD}
  boot:
    admin:
      discovery:
        converter:
          management-context-path: "/config/actuator"

server:
  port: 8888